apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devislex/sync-demo.git
    targetRevision: HEAD
    path: apps/front-end/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
