apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devislex/sync-demo.git
    targetRevision: HEAD
    path: apps/front-end/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
