apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-dev
resources:
  - ../../base
  - namespace.yaml

images:
  - name: nginx
    newTag: "1.23.6"

configMapGenerator:
  - name: app-config
    envs:
      - configmap.env

namePrefix: dev-
commonLabels:
  env: dev

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: front-end
